"""add computed features columns and normalizer params table

Revision ID: 31d734722d27
Revises: 
Create Date: 2026-05-16 11:33:17.133455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d734722d27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_normalizer_params',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('feature_name', sa.String(length=32), nullable=False),
    sa.Column('min_val', sa.Float(), nullable=False),
    sa.Column('max_val', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'isin', 'feature_name')
    )
    op.create_index(op.f('ix_training_normalizer_params_isin'), 'training_normalizer_params', ['isin'], unique=False)
    op.create_index(op.f('ix_training_normalizer_params_job_id'), 'training_normalizer_params', ['job_id'], unique=False)
    op.add_column('esg_scores', sa.Column('esg_b_norm', sa.Float(), nullable=True))
    op.add_column('esg_scores', sa.Column('esg_l_norm', sa.Float(), nullable=True))
    op.add_column('esg_scores', sa.Column('delta_esg', sa.Float(), nullable=True))
    op.add_column('esg_scores', sa.Column('mu_esg', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('return_pct', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('rsi', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('macd_hist', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'macd_hist')
    op.drop_column('market_data', 'rsi')
    op.drop_column('market_data', 'return_pct')
    op.drop_column('esg_scores', 'mu_esg')
    op.drop_column('esg_scores', 'delta_esg')
    op.drop_column('esg_scores', 'esg_l_norm')
    op.drop_column('esg_scores', 'esg_b_norm')
    op.drop_index(op.f('ix_training_normalizer_params_job_id'), table_name='training_normalizer_params')
    op.drop_index(op.f('ix_training_normalizer_params_isin'), table_name='training_normalizer_params')
    op.drop_table('training_normalizer_params')
    # ### end Alembic commands ###
